name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Flutter SDK (subosito/flutter-action is a widely used action for Flutter)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # or pin a specific version like '3.10.6'

      # Cache pub packages to speed up subsequent runs
      - name: Cache Pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      # Lint / analyze the project (Flutter analyzer)
      - name: Analyze project source
        run: flutter analyze

      # Run the regular unit/widget tests
      - name: Run tests
        run: flutter test --machine

      # Optional: collect coverage (uncomment if you want coverage output artifact)
      # - name: Run tests with coverage
      #   run: |
      #     flutter test --coverage
      # - name: Upload coverage (example)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage
      #     path: coverage/lcov.info
